gemfile:
  - web_container/Gemfile
  - components/app_component/Gemfile
script:
  - travis_retry ./test.sh
before_install:
  - cd $(dirname $BUNDLE_GEMFILE)
  - echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' > ~/.bundler_version.sh
  - source ~/.bundler_version.sh
  - gem install bundler
rbenv:
  - 2.5.3
